ECG DATA QUALITY pull request
MD2Korg/stream-processor pull request #77
Opened 2017-05-10 22:04 UTC by aungkonazim

Hi Dr. Hnat,

I have done the ECG data quality computation within the wrapper class.
Since I don't have the  access to data I couldn't run the computation. Although it seems good but without running I can't be too confident on my code.

Can you please run the code at your convenience and let me know. I hope to make everything written by today including respiration code. To allow me make some changes to the constant definitions as Dr. Kumar mentioned I urge you to give me some time in tomorrow morning.

Thanks and Regards
Azim

2017-05-11 01:01 UTC, twhnat requested changes
In general, code should be written to be side-effect free.  Please update your algorithm to resolve these and other noted issues.  We can discuss in the morning if necessary.

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/autosense/AUTOSENSE.java
> +    public static final int QUALITY_outlierThresholdHigh = 4000;
Most of these should be based on a ratio (e.g. 0 <= x <= 1) and combined with the ADC range in the logic.  This ADC should be specified as an input to the processing module

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/features/ECGDataQuality.java
> +        this.acceptableOutlierPercent = AUTOSENSE.QUALITY_acceptableOutlierPercent;
Refactor to just call the constants where needed.  There is no need to introduce additional variables to do this

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/features/ECGDataQuality.java
> +        this.bufferLength = AUTOSENSE.QUALITY_bufferLength;
What is the purpose of a constant 2000 unit buffer?  If this is arbitrary, please use something like ArrayList to handle this without forcing.  See line 87 for an example.

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/features/ECGDataQuality.java
> +        classifyDataPoints(data);
Methods should be written to not have side-effects.  This clearly does due to it not having a return value.

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/features/ECGDataQuality.java
> +        classifySegment(data);
Methods should be written to not have side-effects.  This clearly does due to it not having a return value.

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/features/ECGDataQuality.java
> +        classifyBuffer();
Methods should be written to not have side-effects.  This clearly does due to it not having a return value.

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/features/ECGDataQuality.java
> +        if (segment_class == AUTOSENSE.SEGMENT_BAD) {
segment_class is not defined within this method, further indicating some sort of global state

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/features/ECGDataQuality.java
> +    private void classifyBuffer() {
Should return something

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/features/ECGDataQuality.java
> +        amplitude_small = 0;
For Java, please follow the CamelCase variable naming scheme

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/features/ECGDataQuality.java
> +    private void classifySegment(int[] data) {
Should return something.

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/features/ECGDataQuality.java
> +        if (100 * outliers > acceptableOutlierPercent * data.length) {
Why multiple by 100 here?

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/features/ECGDataQuality.java
> +    private void classifyDataPoints(int[] data){
This should return something

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/features/ECGDataQuality.java
> +            boolean flip=((Math.abs(data[i]-data[im])>4000)||(Math.abs(data[i]-data[ip])>4000));
Constant values should not be here

2017-05-11 01:01 UTC, twhnat commented on src/main/java/md2k/mcerebrum/cstress/features/ECGDataQuality.java
> +            boolean disc=((Math.abs(data[i]-data[im])>100)||(Math.abs(data[i]-data[ip])>100));
Constant values should not be here

2017-05-12 01:51 UTC, aungkonazim commented
Hi Dr. Hnat,

Would you please look at the code at your convenience. I have finalized the code for both ECG and RIP.

Thanks,
Azim

2017-05-13 03:56 UTC, twhnat approved these changes

2017-05-13 03:56 UTC, merged